name: The Rust Programming Language
stable: "1.23.0"
stable_date: "2018-01-04"
stable_blog: "https://blog.rust-lang.org/2018/01/04/Rust-1.23.html"
stable_full_version: "rustc 1.23.0 (766bd11c8 2018-01-01)"
beta: "1.24"
beta_date: "2018-02-15"
nightly: "1.25"
channels:
  - name: "stable"
    vers: "1.23.0"
    package: "1.23.0"
  - name: "beta"
    vers: "1.24"
    package: "beta"
  - name: "nightly"
    vers: "1.25"
    package: "nightly"
